# Deploy on AWS Elastic Beanstalk
name: Node.js Deploy
on:
 push: 
    branches: [main]

jobs:
    deploy:
    runs-on: ubuntu-latest

steps:

 - name: Checkout source code
   uses: actions/checkout@v2

 - name: Generate deployment package
   run: zip -r deploy.zip . -x '*.git*'

 - name: Deploy to EB
   uses: einaregilsson/beanstalk-deploy@v22
   with:
     aws_access_key: ${{ secrets.AKIA5NJVZKPOLKXPX44V }}
     aws_secret_key: ${{ secrets.eJZCJrPPRAbJxUk8WsiZUeVaS35bx5MC1Y/zV9D7 }}
     application_name: MyNodeJSApplication 
     environment_name: MyApplication-Environment
     version_label: 12345
     region: us-east-1
     deployment_package: deploy.zip

# Runs tests as defined in the project's package.json
 run: npm test      
 name: Run test