# Name of the workflow
name: Node.js CD

# Specifies when the workflow should be triggered
on:
  push: 
    branches: [ main ]
# Defines the jobs that the workflow will execute
jobs:
  # Job identifier, can be any name (here it's 'build')
  deploy:
    # Specifies the type of virtual host environment (runner) to use
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it
        uses: actions/checkout@v2

      - # Sets up the specified version of Node.js
        name: Use Node.js 
        uses: actions/setup-node@v2
        with: 
            node-version: '14'
        
      - # Runs tests as defined in the project's package.json
        run: npm test

      - # This command will only run if a build script is defined in the package.json
        run: npm run build
      
      - # Deploys CloudFormation stack using AWS CloudFormation GitHub Action
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: MyNodeJSStack
          template: app.yaml
        

      
